### ISSUE TITLE
[Incompatibility] Crash with Smooth Scrolling

### ISSUE THREAD

**Issue by MidyGamy** [wisp-forest/CondensedCreativeItems#18]
The games crashes when you open the creative inventory with the [Smooth Scrolling](https://modrinth.com/mod/smooth-scroll) mod...

**Comment by MidyGamy** [comment]
I also oppened an issue on their  issue report
https://github.com/SmajloSlovakian/Minecraft-Smooth-Scrolling/issues/48

**Comment by Dragon-Seeker** [comment]
A log of the crash would help figure out exactly the incompatibility

**Comment by MidyGamy** [comment]
[crash-2024-08-07_15.49.33-client.txt](https://github.com/user-attachments/files/16529585/crash-2024-08-07_15.49.33-client.txt)

**Comment by SmajloSlovakian** [comment]
hi, i'm the developer of smooth scrolling

i have now fixed the crash in my dev branch but most non-vanilla stuff you add is still broken (doesn't scroll smoothly and some minor unexpected issues occur)... maybe i can fix it by using matrixtransform instead of modifying the render positions of items... i think that you don't need to do anything to fix the issues

**Comment by SmajloSlovakian** [comment]
most of the issues (if not all) will be fixed in smooth scrolling version 2.1.3 without the need to update this mod.

**Comment by SmajloSlovakian** [comment]
i would like to fix one more issue though... so where can i get the items from your mod for any position in the tab? if i don't get them, the items will either mismatch sometimes when scrolling at the top or bottom or instantly disappear... i want to use that in my mixins/handledscreenmixin at around line 67 in my code

**Comment by Dragon-Seeker** [comment]
Sorry for not getting back to you on this issue as I have been busy with other mods and life stuff to say the least. I have made a PR that contains fixes for the issues outlined for 3.4.0: https://github.com/SmajloSlovakian/Minecraft-Smooth-Scrolling/pull/49

**Comment by SmajloSlovakian** [comment]
sorry you had to put up with my garbage code spaghetti and thanks for the pr... i'm now gonna try it and i may make some changes to it if i see fit... i make no promises that i will abide by the rules you just applied to the whole project by i'll try :)... thanks

**Comment by SmajloSlovakian** [comment]
there is just one problem: it can't find io.wispforest.condensed_creative.entry.EntryContainer... it does find everything else but this one line errors out and so minecraft crashes with these two mods when i open creative inventory... i'll try to fix it myself but if you know what should be done, feel free to tell

**Comment by SmajloSlovakian** [comment]
well the two overrides are also erroring out because the class is not extending anything

**Comment by Dragon-Seeker** [comment]
Hmmm odd, try refreshing gradle as it worked for me and the files should be within the latest CC version

**Comment by SmajloSlovakian** [comment]
i'll be able to try it out again tomorrow or later... and i don't see the file on your github so idk...

**Comment by SmajloSlovakian** [comment]
oh i think i see that you don't have it updated on github so that's why i don't see it... well then idk how it would use a lower version of your mod... gradle is weird...

**Comment by Dragon-Seeker** [comment]
Pushed the changes to Github btw

**Comment by SmajloSlovakian** [comment]
tried it out with version 3.4.0 in the run/mods folder... it now does this when i go to the second page of creative inventory, go down and go up... it is also a bit inconsistent on if it will render the mod's item entries or vanilla's on the end of the scrolling...

   ---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2024-08-18 17:39:10
Description: Rendering screen

java.lang.ClassCastException: class smsk.smoothscroll.compat.CondensedInventoryCompat$CondensedEntryDelegatingInventory cannot be cast to class io.wispforest.condensed_creative.util.CondensedInventory (smsk.smoothscroll.compat.CondensedInventoryCompat$CondensedEntryDelegatingInventory and io.wispforest.condensed_creative.util.CondensedInventory are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @97e1986)
        at io.wispforest.condensed_creative.client.SlotRenderUtils.isSlotAbovePartOfCondensedEntry(SlotRenderUtils.java:77)
        at io.wispforest.condensed_creative.client.SlotRenderUtils.renderExtraIfEntry(SlotRenderUtils.java:48)
        at net.minecraft.client.gui.screen.ingame.HandledScreen.wrapOperation$zjp000$condensed_creative$renderExtraIfEntry(HandledScreen.java:1714)
        at net.minecraft.client.gui.screen.ingame.HandledScreen.wrapOperation$zjp000$condensed_creative$renderExtraIfEntry$mixinextras$bridge$47(HandledScreen.java)
        at net.minecraft.client.gui.screen.ingame.HandledScreen.drawSlot(HandledScreen.java:259)
        at net.minecraft.client.gui.screen.ingame.HandledScreen.drawSlotOverridden(HandledScreen.java:772)
        at net.minecraft.client.gui.screen.ingame.HandledScreen.handler$zph000$smoothscroll$renderMid0(HandledScreen.java:765)
        at net.minecraft.client.gui.screen.ingame.HandledScreen.render(HandledScreen.java:105)
        at net.minecraft.client.gui.screen.ingame.AbstractInventoryScreen.render(AbstractInventoryScreen.java:32)
        at net.minecraft.client.gui.screen.ingame.CreativeInventoryScreen.render(CreativeInventoryScreen.java:778)
        at net.minecraft.client.gui.screen.Screen.renderWithTooltip(Screen.java:117)
        at net.minecraft.client.render.GameRenderer.mixinextras$bridge$renderWithTooltip$177(GameRenderer.java)
        at net.minecraft.client.render.GameRenderer.wrapOperation$zkf000$fabric-screen-api-v1$onRenderScreen(GameRenderer.java:2086)
        at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:913)
        at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1285)
        at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:882)
        at net.minecraft.client.main.Main.main(Main.java:256)
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
        at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
        at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
        at io.wispforest.condensed_creative.client.SlotRenderUtils.isSlotAbovePartOfCondensedEntry(SlotRenderUtils.java:77)
        at io.wispforest.condensed_creative.client.SlotRenderUtils.renderExtraIfEntry(SlotRenderUtils.java:48)
        at net.minecraft.client.gui.screen.ingame.HandledScreen.wrapOperation$zjp000$condensed_creative$renderExtraIfEntry(HandledScreen.java:1714)
        at net.minecraft.client.gui.screen.ingame.HandledScreen.wrapOperation$zjp000$condensed_creative$renderExtraIfEntry$mixinextras$bridge$47(HandledScreen.java)
        at net.minecraft.client.gui.screen.ingame.HandledScreen.drawSlot(HandledScreen.java:259)
        at net.minecraft.client.gui.screen.ingame.HandledScreen.drawSlotOverridden(HandledScreen.java:772)
        at net.minecraft.client.gui.screen.ingame.HandledScreen.handler$zph000$smoothscroll$renderMid0(HandledScreen.java:765)
        at net.minecraft.client.gui.screen.ingame.HandledScreen.render(HandledScreen.java:105)
        at net.minecraft.client.gui.screen.ingame.AbstractInventoryScreen.render(AbstractInventoryScreen.java:32)
        at net.minecraft.client.gui.screen.ingame.CreativeInventoryScreen.render(CreativeInventoryScreen.java:778)
        at net.minecraft.client.gui.screen.Screen.renderWithTooltip(Screen.java:117)
        at net.minecraft.client.render.GameRenderer.mixinextras$bridge$renderWithTooltip$177(GameRenderer.java)
        at net.minecraft.client.render.GameRenderer.wrapOperation$zkf000$fabric-screen-api-v1$onRenderScreen(GameRenderer.java:2086)

-- Screen render details --
Details:
        Screen name: net.minecraft.client.gui.screen.ingame.CreativeInventoryScreen
        Mouse location: Scaled: (357, 148). Absolute: (1428.000000, 592.000000)
        Screen size: Scaled: (480, 270). Absolute: (1920, 1080). Scale factor of 4.000000
Stacktrace:
        at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:913)
        at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1285)
        at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:882)
        at net.minecraft.client.main.Main.main(Main.java:256)
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
        at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
        at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

-- Uptime --
Details:
        JVM uptime: 61.303s
        Wall uptime: 46.045s
        High-res time: 44.251s
        Client ticks: 802 ticks / 40.100s
Stacktrace:
        at net.minecraft.client.MinecraftClient.addDetailsToCrashReport(MinecraftClient.java:2501)
        at net.minecraft.client.MinecraftClient.printCrashReport(MinecraftClient.java:949)
        at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:902)
        at net.minecraft.client.main.Main.main(Main.java:256)
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
        at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
        at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

-- Affected level --
Details:
        All players: 1 total; [ClientPlayerEntity['Player540'/12, l='ClientLevel', x=0.38, y=-60.00, z=-12.75]]
        Chunk stats: 625, 381
        Level dimension: minecraft:overworld
        Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
        Level time: 972543 game time, 214715 day time
        Server brand: fabric
        Server type: Integrated singleplayer server
        Tracked entity count: 23

-- Last reload --
Details:
        Reload number: 1
        Reload reason: initial
        Finished: Yes
        Packs: vanilla, fabric, cloth-config, condensed_creative, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, highlight_item, modmenu, prism, smoothscroll, sounds, yet_another_config_lib_v3

-- System Details --
Details:
        Minecraft Version: 1.21
        Minecraft Version ID: 1.21
        Operating System: Linux (amd64) version 6.9.12-200.fc40.x86_64
        Java Version: 21.0.4, Red Hat, Inc.
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Red Hat, Inc.
        Memory: 296922008 bytes (283 MiB) / 926941184 bytes (884 MiB) up to 6132072448 bytes (5848 MiB)
        CPUs: 12
        Processor Vendor: AuthenticAMD
        Processor Name: AMD Ryzen 5 4600H with Radeon Graphics
        Identifier: AuthenticAMD Family 23 Model 96 Stepping 1
        Microarchitecture: unknown
        Frequency (GHz): -0.00
        Number of physical packages: 1
        Number of physical CPUs: 6
        Number of logical CPUs: 12
        Graphics card #0 name: TU117M [GeForce GTX 1650 Ti Mobile]
        Graphics card #0 vendor: NVIDIA Corporation (0x10de)
        Graphics card #0 VRAM (MiB): 288.00
        Graphics card #0 deviceId: 0x1f95
        Graphics card #0 versionInfo: unknown
        Graphics card #1 name: Renoir [Radeon Vega Series / Radeon Vega Mobile Series]
        Graphics card #1 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
        Graphics card #1 VRAM (MiB): 258.00
        Graphics card #1 deviceId: 0x1636
        Graphics card #1 versionInfo: unknown
        Virtual memory max (MiB): 19885.85
        Virtual memory used (MiB): 8469.14
        Swap memory total (MiB): 8192.00
        Swap memory used (MiB): 0.00
        Space in storage for jna.tmpdir (MiB): <path not set>
        Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
        Space in storage for io.netty.native.workdir (MiB): <path not set>
        Space in storage for java.io.tmpdir (MiB): available: 11686.83, total: 11693.86
        Space in storage for workdir (MiB): available: 68504.66, total: 100000.00
        JVM Flags: 0 total; 
        Fabric Mods: 
                cloth-config: Cloth Config v15 15.0.128
                        cloth-basic-math: cloth-basic-math 0.6.1
                condensed_creative: Condensed Creative 3.4.0+1.21
                fabric-api: Fabric API 0.100.1+1.21
                        fabric-api-base: Fabric API Base 0.4.42+6573ed8c90
                        fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.65+b559734490
                        fabric-biome-api-v1: Fabric Biome API (v1) 13.0.28+6fc22b9990
                        fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a790
                        fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c90
                        fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a790
                        fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c90
                        fabric-command-api-v1: Fabric Command API (v1) 1.2.48+f71b366f90
                        fabric-command-api-v2: Fabric Command API (v2) 2.2.27+6a6dfa1990
                        fabric-commands-v0: Fabric Commands (v0) 0.2.65+df3654b390
                        fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.11+b559734490
                        fabric-convention-tags-v1: Fabric Convention Tags 2.0.12+7f945d5b90
                        fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.2.1+d153f34490
                        fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a790
                        fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.22+6a6dfa1990
                        fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.6+16c4ae2590
                        fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9990
                        fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b9990
                        fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.10+e633f88390
                        fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.52+6573ed8c90
                        fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc92190
                        fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.0+00ab0a6390
                        fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a790
                        fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b390
                        fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.9+98a7dbbb90
                        fabric-loot-api-v2: Fabric Loot API (v2) 3.0.9+6573ed8c90
                        fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c90
                        fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b90
                        fabric-networking-api-v1: Fabric Networking API (v1) 4.1.0+686dcdce90
                        fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.10+d132107690
                        fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c90
                        fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.8+6573ed8c90
                        fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.21+b9828ba390
                        fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.16+fe474d6b90
                        fabric-renderer-indigo: Fabric Renderer - Indigo 1.6.3+cc9f121a90
                        fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.66+df3654b390
                        fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e90
                        fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b559734490
                        fabric-rendering-v0: Fabric Rendering (v0) 1.1.69+df3654b390
                        fabric-rendering-v1: Fabric Rendering (v1) 5.0.3+d132107690
                        fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.2.1+d153f34490
                        fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.1.3+b559734490
                        fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b559734490
                        fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.78+b559734490
                        fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c90
                        fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.12+b559734490
                        fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.12+6573ed8c90
                fabricloader: Fabric Loader 0.15.11
                highlight_item: Highlight Item 1.2.0
                iceberg: Iceberg 1.2.4
                itemborders: Item Borders 1.2.5
                java: OpenJDK 64-Bit Server VM 21
                minecraft: Minecraft 1.21
                mixinextras: MixinExtras 0.3.5
                modmenu: Mod Menu 11.0.1
                        placeholder-api: Placeholder API 2.4.0-pre.2+1.21
                mru: Mineblock's Repeated Utilities 0.4.4+1.21
                prism: root project 'Prism' 1.0.8
                smoothscroll: Smooth Scroll 2.1.3
                smoothscrollingrefurbished: Smooth Scrolling Refurbished 1.1.4
                sounds: Sounds 1.1.3+1.21
                        yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.21-fabric
                                com_twelvemonkeys_common_common-image: common-image 3.10.0
                                com_twelvemonkeys_common_common-io: common-io 3.10.0
                                com_twelvemonkeys_common_common-lang: common-lang 3.10.0
                                com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
                                com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
                                com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
                                org_quiltmc_parsers_gson: gson 0.2.1
                                org_quiltmc_parsers_json: json 0.2.1
        Launched Version: Fabric
        Backend library: LWJGL version 3.3.3-snapshot
        Backend API: AMD Radeon Graphics (radeonsi, renoir, LLVM 18.1.6, DRM 3.57, 6.9.12-200.fc40.x86_64) GL version 4.6 (Core Profile) Mesa 24.1.5, AMD
        Window size: 1920x1080
        GFLW Platform: x11
        GL Caps: Using framebuffer using OpenGL 3.2
        GL debug messages: 
        Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
        Universe: 400921fb54442d18
        Type: Integrated Server (map_client.txt)
        Graphics mode: fancy
        Render Distance: 9/9 chunks
        Resource Packs: vanilla, fabric, cloth-config, condensed_creative, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, highlight_item, modmenu, prism, smoothscroll, sounds, yet_another_config_lib_v3 (incompatible)
        Current Language: en_us
        Locale: sk_SK
        System encoding: UTF-8
        File encoding: UTF-8
        CPU: 12x AMD Ryzen 5 4600H with Radeon Graphics
        Server Running: true
        Player Count: 1 / 8; [ServerPlayerEntity['Player540'/12, l='ServerLevel[New World]', x=0.38, y=-60.00, z=-12.75]]
        Active Data Packs: vanilla, fabric, fabric-convention-tags-v2
        Available Data Packs: bundle, fabric, fabric-convention-tags-v2, trade_rebalance, vanilla
        Enabled Feature Flags: minecraft:vanilla
        World Generation: Stable
        World Seed: -4871776920978740266
#@!@# Game crashed! Crash report saved to: #@!@# /home/SmajloSlovakian/Plocha/Minecraft-Smooth-Scrolling/run/crash-reports/crash-2024-08-18_17.39.10-client.txt
<===========--> 90% EXECUTING [1m 9s]
> :runClient

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runClient'.
> Process 'command '/usr/lib/jvm/java-21-openjdk-21.0.4.0.7-2.fc40.x86_64/bin/java'' finished with non-zero exit value 255

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

> Task :runClient FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.8/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
7 actionable tasks: 7 executed
Could not execute build using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-8.8-bin.zip'.
 *  The terminal process terminated with exit code: 1.

**Comment by Dragon-Seeker** [comment]
Ah that is my bad as I messed up with not removing the direct casts for `CondensedInventory` instead of `EntryContainer` in some code leading to issues.

**Comment by Dragon-Seeker** [comment]
Pushed an update for such hopefully fixing the crash

**Comment by SmajloSlovakian** [comment]
crashes are all fixed... but the trailing smooth scrolling items are still inconsistant - at least on the first two pages it just tends to copy one item all over the row for some reason but on other tabs it works great (aside from one small issue that the item backgrounds aren't joined and have a blue line between them - i don't expect you to fix that)... so that thing i would like you to fix properly because i don't think i'm able to do that... btw you can set the creative screen smooth scrolling speed to 0.99 in the config file of my mod and then reload resources so you can see the issue more easily
