### ISSUE TITLE
`IndexOutOfBoundsException: Index 0 out of bounds for length 0`

### ISSUE THREAD

**Issue by SettingDust** [wisp-forest/CondensedCreativeItems#9]
https://mclo.gs/rA9VHD7
```
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'condensed_creative'!
	at app//org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:66)
	at app//org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:34)
	at app//org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:64)
	at app//org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:49)
	at app//org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at app//org.quiltmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:56)
	at MC//net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:458)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at java.base@17.0.8/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.8/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.8/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.8/java.lang.reflect.Method.invoke(Method.java:568)
	at app//org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524)
	at app//org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82)
	at app//org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at app//org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at app//org.prismlauncher.EntryPoint.listen(EntryPoint.java:125)
	at app//org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base@17.0.8/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base@17.0.8/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base@17.0.8/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base@17.0.8/java.util.Objects.checkIndex(Objects.java:361)
	at java.base@17.0.8/java.util.ArrayList.get(ArrayList.java:427)
	at io.wispforest.condensed_creative.data.BuiltinEntries.lambda$registerBuiltinEntries$14(BuiltinEntries.java:98)
	at app//it.unimi.dsi.fastutil.objects.ObjectArraySet$Spliterator.forEachRemaining(ObjectArraySet.java:294)
	at java.base@17.0.8/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at io.wispforest.condensed_creative.data.BuiltinEntries.registerBuiltinEntries(BuiltinEntries.java:78)
	at io.wispforest.condensed_creative.CondensedCreative.onInitializeCondensedEntries(CondensedCreative.java:63)
	at io.wispforest.condensed_creative.CondensedCreative.onInitializeClient(CondensedCreative.java:51)
	at io.wispforest.condensed_creative.fabriclike.CondensedCreativeFabricLike.onInitializeClient(CondensedCreativeFabricLike.java:16)
	at io.wispforest.condensed_creative.fabric.CondensedCreativeFabric.onInitializeClient(CondensedCreativeFabric.java:20)
	at app//org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startClient$1(Hooks.java:56)
	at app//org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:36)
	at app//org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:62)
	... 15 more
```

**Comment by Dragon-Seeker** [comment]
Hmm, I see where I went wrong as I assumed that people would follow similar methods of Vanilla wood types which led to finding nothing within the registry and an empty list. Will rethink such for the future but 8672b3c54a42c2486457ae4c45215f0ac9b45b8e should fix that issue. You can wait for the latest github action to confirm such is no longer a problem

**Comment by SettingDust** [comment]
It's from Cobblemon

[CondensedCreative]: Attempted to create a builtin entry for the given WoodType [class_4719[name=apricorn, setType=class_8177[name=apricorn, canOpenByHand=true, soundType=net.minecraft.class_2498@4431d7c8, doorClose=net.minecraft.class_3414@c04ab48, doorOpen=net.minecraft.class_3414@1801aaef, trapdoorClose=net.minecraft.class_3414@31311a5, trapdoorOpen=net.minecraft.class_3414@5620a340, pressurePlateClickOff=net.minecraft.class_3414@7d3a52aa, pressurePlateClickOn=net.minecraft.class_3414@621be873, buttonClickOff=net.minecraft.class_3414@42449a0b, buttonClickOn=net.minecraft.class_3414@4b6cb496], soundType=net.minecraft.class_2498@4431d7c8, hangingSignSoundType=net.minecraft.class_2498@2f92de5a, fenceGateClose=net.minecraft.class_3414@50e43637, fenceGateOpen=net.minecraft.class_3414@44946197]] but was unable to find the registry entries!

**Comment by Dragon-Seeker** [comment]
I have made an update to the given log output to be less intrusive.
